[2025-05-21T07:52:24.400+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_snowflake.consume_kafka_and_store_in_snowflake manual__2025-05-21T07:52:22.765200+00:00 [queued]>
[2025-05-21T07:52:24.407+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_snowflake.consume_kafka_and_store_in_snowflake manual__2025-05-21T07:52:22.765200+00:00 [queued]>
[2025-05-21T07:52:24.408+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-21T07:52:24.417+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): consume_kafka_and_store_in_snowflake> on 2025-05-21 07:52:22.765200+00:00
[2025-05-21T07:52:24.421+0000] {standard_task_runner.py:57} INFO - Started process 389 to run task
[2025-05-21T07:52:24.425+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_snowflake', 'consume_kafka_and_store_in_snowflake', 'manual__2025-05-21T07:52:22.765200+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/kafka_to_snowflake.py', '--cfg-path', '/tmp/tmp3dhpqwyx']
[2025-05-21T07:52:24.428+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask consume_kafka_and_store_in_snowflake
[2025-05-21T07:52:24.448+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T07:52:24.471+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_to_snowflake.consume_kafka_and_store_in_snowflake manual__2025-05-21T07:52:22.765200+00:00 [running]> on host 8b20e5ff94cb
[2025-05-21T07:52:24.514+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_snowflake' AIRFLOW_CTX_TASK_ID='consume_kafka_and_store_in_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T07:52:22.765200+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T07:52:22.765200+00:00'
[2025-05-21T07:52:24.516+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:52:24.516+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:24.516+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:24.517+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:52:24.517+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:24.517+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:24.517+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.06 secs
[2025-05-21T07:52:24.577+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:52:24.577+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:24.577+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:24.578+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:52:24.578+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:24.578+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:24.578+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.11 secs
[2025-05-21T07:52:24.693+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:52:24.694+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:24.694+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:24.695+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:52:24.695+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:24.696+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:24.696+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.22 secs
[2025-05-21T07:52:24.921+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:52:24.922+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:24.923+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:24.924+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:52:24.924+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:24.924+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:24.925+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.35 secs
[2025-05-21T07:52:25.281+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:52:25.282+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:25.282+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:25.283+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:52:25.283+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:25.283+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:25.283+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.87 secs
[2025-05-21T07:52:26.154+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:52:26.157+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:26.157+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:26.157+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:52:26.158+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:26.158+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:26.158+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.36 secs
[2025-05-21T07:52:26.517+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 27, in consume_and_load
    consumer = KafkaConsumer(
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/consumer/group.py", line 387, in __init__
    self._client = self.config['kafka_client'](metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-05-21T07:52:26.529+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_to_snowflake, task_id=consume_kafka_and_store_in_snowflake, execution_date=20250521T075222, start_date=20250521T075224, end_date=20250521T075226
[2025-05-21T07:52:26.544+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task consume_kafka_and_store_in_snowflake (NoBrokersAvailable; 389)
[2025-05-21T07:52:26.572+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-21T07:52:26.590+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
