[2025-05-21T07:19:58.231+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_snowflake.consume_kafka_and_store_in_snowflake scheduled__2025-05-21T06:00:00+00:00 [queued]>
[2025-05-21T07:19:58.236+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_snowflake.consume_kafka_and_store_in_snowflake scheduled__2025-05-21T06:00:00+00:00 [queued]>
[2025-05-21T07:19:58.237+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-05-21T07:19:58.245+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): consume_kafka_and_store_in_snowflake> on 2025-05-21 06:00:00+00:00
[2025-05-21T07:19:58.249+0000] {standard_task_runner.py:57} INFO - Started process 300 to run task
[2025-05-21T07:19:58.251+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_snowflake', 'consume_kafka_and_store_in_snowflake', 'scheduled__2025-05-21T06:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/kafka_to_snowflake.py', '--cfg-path', '/tmp/tmp91eyp3ef']
[2025-05-21T07:19:58.254+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask consume_kafka_and_store_in_snowflake
[2025-05-21T07:19:58.265+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T07:19:58.290+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_to_snowflake.consume_kafka_and_store_in_snowflake scheduled__2025-05-21T06:00:00+00:00 [running]> on host e59c1544f2e4
[2025-05-21T07:19:58.331+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_snowflake' AIRFLOW_CTX_TASK_ID='consume_kafka_and_store_in_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-21T06:00:00+00:00'
[2025-05-21T07:19:58.333+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 27, in consume_and_load
    consumer = KafkaConsumer(
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/consumer/group.py", line 387, in __init__
    self._client = self.config['kafka_client'](metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 234, in __init__
    self.cluster = ClusterMetadata(**self.config)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/cluster.py", line 70, in __init__
    self._bootstrap_brokers = self._generate_bootstrap_brokers()
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/cluster.py", line 75, in _generate_bootstrap_brokers
    bootstrap_hosts = collect_hosts(self.config['bootstrap_servers'])
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/cluster.py", line 439, in collect_hosts
    for host_port in hosts:
TypeError: 'NoneType' object is not iterable
[2025-05-21T07:19:58.339+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=kafka_to_snowflake, task_id=consume_kafka_and_store_in_snowflake, execution_date=20250521T060000, start_date=20250521T071958, end_date=20250521T071958
[2025-05-21T07:19:58.345+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task consume_kafka_and_store_in_snowflake ('NoneType' object is not iterable; 300)
[2025-05-21T07:19:58.351+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-21T07:19:58.360+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T07:37:44.937+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_snowflake.consume_kafka_and_store_in_snowflake scheduled__2025-05-21T06:00:00+00:00 [queued]>
[2025-05-21T07:37:44.944+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_snowflake.consume_kafka_and_store_in_snowflake scheduled__2025-05-21T06:00:00+00:00 [queued]>
[2025-05-21T07:37:44.944+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-05-21T07:37:44.952+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): consume_kafka_and_store_in_snowflake> on 2025-05-21 06:00:00+00:00
[2025-05-21T07:37:44.961+0000] {standard_task_runner.py:57} INFO - Started process 270 to run task
[2025-05-21T07:37:44.965+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_snowflake', 'consume_kafka_and_store_in_snowflake', 'scheduled__2025-05-21T06:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/kafka_to_snowflake.py', '--cfg-path', '/tmp/tmpscnufc1f']
[2025-05-21T07:37:44.969+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask consume_kafka_and_store_in_snowflake
[2025-05-21T07:37:44.991+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T07:37:45.042+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_to_snowflake.consume_kafka_and_store_in_snowflake scheduled__2025-05-21T06:00:00+00:00 [running]> on host 438ab5e4831f
[2025-05-21T07:37:45.086+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_snowflake' AIRFLOW_CTX_TASK_ID='consume_kafka_and_store_in_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-21T06:00:00+00:00'
[2025-05-21T07:37:45.088+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:37:45.090+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.090+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.090+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:37:45.090+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.090+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.091+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.04 secs
[2025-05-21T07:37:45.139+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:37:45.139+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.139+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.140+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:37:45.140+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.140+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.140+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.10 secs
[2025-05-21T07:37:45.244+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:37:45.245+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.245+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.246+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:37:45.246+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.247+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.247+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.24 secs
[2025-05-21T07:37:45.489+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:37:45.491+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.492+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.492+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:37:45.493+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.493+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.494+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.35 secs
[2025-05-21T07:37:45.853+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:37:45.853+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.854+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.854+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:37:45.854+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.855+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.855+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.66 secs
[2025-05-21T07:37:46.524+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:37:46.526+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:46.526+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:46.527+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:37:46.527+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:46.528+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:46.528+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.56 secs
[2025-05-21T07:37:47.091+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 27, in consume_and_load
    consumer = KafkaConsumer(
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/consumer/group.py", line 387, in __init__
    self._client = self.config['kafka_client'](metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-05-21T07:37:47.109+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=kafka_to_snowflake, task_id=consume_kafka_and_store_in_snowflake, execution_date=20250521T060000, start_date=20250521T073744, end_date=20250521T073747
[2025-05-21T07:37:47.120+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task consume_kafka_and_store_in_snowflake (NoBrokersAvailable; 270)
[2025-05-21T07:37:47.148+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-21T07:37:47.163+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T07:54:27.433+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_snowflake.consume_kafka_and_store_in_snowflake scheduled__2025-05-21T06:00:00+00:00 [queued]>
[2025-05-21T07:54:27.439+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_snowflake.consume_kafka_and_store_in_snowflake scheduled__2025-05-21T06:00:00+00:00 [queued]>
[2025-05-21T07:54:27.439+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-05-21T07:54:27.446+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): consume_kafka_and_store_in_snowflake> on 2025-05-21 06:00:00+00:00
[2025-05-21T07:54:27.450+0000] {standard_task_runner.py:57} INFO - Started process 444 to run task
[2025-05-21T07:54:27.461+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_snowflake', 'consume_kafka_and_store_in_snowflake', 'scheduled__2025-05-21T06:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/kafka_to_snowflake.py', '--cfg-path', '/tmp/tmpr9ejf6mw']
[2025-05-21T07:54:27.467+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask consume_kafka_and_store_in_snowflake
[2025-05-21T07:54:27.483+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T07:54:27.511+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_to_snowflake.consume_kafka_and_store_in_snowflake scheduled__2025-05-21T06:00:00+00:00 [running]> on host 8b20e5ff94cb
[2025-05-21T07:54:27.557+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_snowflake' AIRFLOW_CTX_TASK_ID='consume_kafka_and_store_in_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-21T06:00:00+00:00'
[2025-05-21T07:54:27.560+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:54:27.561+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:54:27.561+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:54:27.561+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:54:27.561+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:54:27.561+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:54:27.561+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.05 secs
[2025-05-21T07:54:27.615+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:54:27.616+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:54:27.616+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:54:27.616+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:54:27.616+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:54:27.616+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:54:27.616+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.10 secs
[2025-05-21T07:54:27.715+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:54:27.716+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:54:27.716+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:54:27.717+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:54:27.717+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:54:27.717+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:54:27.718+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.18 secs
[2025-05-21T07:54:27.903+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:54:27.904+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:54:27.904+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:54:27.905+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:54:27.905+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:54:27.906+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:54:27.906+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.45 secs
[2025-05-21T07:54:28.360+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:54:28.363+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:54:28.363+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:54:28.363+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:54:28.364+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:54:28.364+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:54:28.365+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.92 secs
[2025-05-21T07:54:29.287+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:54:29.290+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:54:29.291+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:54:29.291+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:54:29.292+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:54:29.293+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:54:29.293+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.27 secs
[2025-05-21T07:54:29.562+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 27, in consume_and_load
    consumer = KafkaConsumer(
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/consumer/group.py", line 387, in __init__
    self._client = self.config['kafka_client'](metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-05-21T07:54:29.577+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=kafka_to_snowflake, task_id=consume_kafka_and_store_in_snowflake, execution_date=20250521T060000, start_date=20250521T075427, end_date=20250521T075429
[2025-05-21T07:54:29.591+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task consume_kafka_and_store_in_snowflake (NoBrokersAvailable; 444)
[2025-05-21T07:54:29.601+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-21T07:54:29.615+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
