[2025-05-21T07:37:44.937+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_snowflake.consume_kafka_and_store_in_snowflake manual__2025-05-21T07:35:39.798349+00:00 [queued]>
[2025-05-21T07:37:44.944+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_snowflake.consume_kafka_and_store_in_snowflake manual__2025-05-21T07:35:39.798349+00:00 [queued]>
[2025-05-21T07:37:44.945+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-05-21T07:37:44.953+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): consume_kafka_and_store_in_snowflake> on 2025-05-21 07:35:39.798349+00:00
[2025-05-21T07:37:44.960+0000] {standard_task_runner.py:57} INFO - Started process 271 to run task
[2025-05-21T07:37:44.963+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_snowflake', 'consume_kafka_and_store_in_snowflake', 'manual__2025-05-21T07:35:39.798349+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/kafka_to_snowflake.py', '--cfg-path', '/tmp/tmp1dfzhqql']
[2025-05-21T07:37:44.968+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask consume_kafka_and_store_in_snowflake
[2025-05-21T07:37:44.989+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T07:37:45.032+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_to_snowflake.consume_kafka_and_store_in_snowflake manual__2025-05-21T07:35:39.798349+00:00 [running]> on host 438ab5e4831f
[2025-05-21T07:37:45.078+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_snowflake' AIRFLOW_CTX_TASK_ID='consume_kafka_and_store_in_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T07:35:39.798349+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T07:35:39.798349+00:00'
[2025-05-21T07:37:45.082+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:37:45.083+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.084+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.084+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:37:45.084+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.084+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.085+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.05 secs
[2025-05-21T07:37:45.142+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:37:45.143+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.143+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.143+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:37:45.143+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.144+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.144+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.09 secs
[2025-05-21T07:37:45.244+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:37:45.245+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.245+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.246+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:37:45.246+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.247+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.247+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.21 secs
[2025-05-21T07:37:45.467+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:37:45.470+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.472+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.472+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:37:45.473+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.474+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.474+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.34 secs
[2025-05-21T07:37:45.817+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:37:45.818+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.819+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.819+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:37:45.819+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:45.819+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:45.820+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.95 secs
[2025-05-21T07:37:46.773+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:37:46.774+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:46.775+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:46.775+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:37:46.776+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:37:46.776+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:37:46.776+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.30 secs
[2025-05-21T07:37:47.089+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 27, in consume_and_load
    consumer = KafkaConsumer(
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/consumer/group.py", line 387, in __init__
    self._client = self.config['kafka_client'](metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-05-21T07:37:47.109+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=kafka_to_snowflake, task_id=consume_kafka_and_store_in_snowflake, execution_date=20250521T073539, start_date=20250521T073744, end_date=20250521T073747
[2025-05-21T07:37:47.119+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task consume_kafka_and_store_in_snowflake (NoBrokersAvailable; 271)
[2025-05-21T07:37:47.151+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-21T07:37:47.164+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
